# -*- coding: utf-8 -*-
"""DataLoading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hczibn-2oB1P8cHTu9OyT5E-KRoDxVi7
"""

from torchvision import transforms
from torch.utils.data import DataLoader
import os
from SPOTDatasetLoader import SPOTDataLoader

TRAIN_PATH = 'path/to/TRAIN/folder'
TEST_PATH = 'path/to/TEST/folder'
goal_folder = 'path/to/goal/folder'


data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])


train_dataset = SPOTDataLoader(
    root_dir=TRAIN_PATH,
    goal_folder=goal_folder,
    labels_file=os.path.join(TRAIN_PATH, 'labels.npy'),
    transform=data_transforms
)

test_dataset = SPOTDataLoader(
    root_dir=TEST_PATH,
    goal_folder=goal_folder,
    labels_file=os.path.join(TEST_PATH, 'labels.npy'),
    transform=data_transforms
)


train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)